apiVersion: batch/v1
kind: Job
metadata:
  name: spv2-process-cpu-dev
  namespace: s2-spv2-dev
  labels:
    contact: dirkg
spec:
  parallelism: 8
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: spv2-process-dev
          image: 896129387501.dkr.ecr.us-west-2.amazonaws.com/spv2/process-cpu:1.0.dev
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 16
              memory: 16Gi
            requests:
              cpu: 7
              memory: 8Gi
